// packages/react/examples/demo/App.tsx
// @faqir-ui/react demo — task 0.7-02 acceptance ("example page with ≥ 5
// components verified against the real CSS bundle"). Composes seven interactive
// recipes (dialog, alert-dialog, tabs, tooltip, pagination, slider, accordion)
// plus a handful of primitives, styled ONLY by the shipped Faqir CSS bundle
// (no className, no inline styling — the data-ui/data-part contract is the API).
// Note the React slot convention: a recipe's named parts are PROPS
// (`<LCard title={…} body={…} />`), while a bring-your-own recipe (tabs,
// accordion) takes `children` that replace the whole anatomy. Served by
// ./serve.ts; mounted under <StrictMode> so the create→destroy→create effect
// double-invoke is exercised against a real browser too.

import { useRef, useState } from "react";
import type { RecipeHandle } from "../../src/index";
import {
  LDialog,
  LAlertDialog,
  LTabs,
  LTooltip,
  LPagination,
  LSlider,
  LAccordion,
  LButton,
  LCard,
  LBadge,
  LStack,
  LText,
  LSeparator,
} from "../../src/index";

export default function App() {
  const dialog = useRef<RecipeHandle & { open: () => void }>(null);
  const alert = useRef<RecipeHandle & { open: () => void }>(null);
  const [page, setPage] = useState(1);
  const [confirmed, setConfirmed] = useState<string | null>(null);

  return (
    <LStack gap="6">
      <LText size="xl" weight="bold">
        @faqir-ui/react — recipes against the real CSS bundle
      </LText>

      <LCard
        title={<LText weight="semibold">Dialog + Alert dialog (imperative handle)</LText>}
        body={
          <LStack gap="4">
            <LStack variant="horizontal" gap="2">
              <LButton variant="primary" onClick={() => dialog.current?.open()}>
                Open dialog
              </LButton>
              <LButton variant="destructive" onClick={() => alert.current?.open()}>
                Delete…
              </LButton>
              {confirmed && <LBadge variant="success">{confirmed}</LBadge>}
            </LStack>

            <LDialog
              ref={dialog}
              title="Edit profile"
              body={<LText>Everything here is styled by the Faqir bundle.</LText>}
              footer={
                <LButton variant="primary" data-part="close">
                  Done
                </LButton>
              }
            />

            <LAlertDialog
              ref={alert}
              title="Delete this item?"
              body={<LText>This action cannot be undone.</LText>}
              onConfirm={() => setConfirmed("Deleted")}
              onCancel={() => setConfirmed("Cancelled")}
            />
          </LStack>
        }
      />

      <LCard
        title={<LText weight="semibold">Tabs</LText>}
        body={
          <LTabs>
            <div data-part="list" role="tablist">
              <button data-part="trigger" role="tab" aria-selected="true">
                Overview
              </button>
              <button data-part="trigger" role="tab" aria-selected="false">
                Activity
              </button>
            </div>
            <div data-part="panel" role="tabpanel">
              The recipe wrapper renders this markup; its controller wires the roving tabs.
            </div>
            <div data-part="panel" role="tabpanel" hidden>
              Second panel content.
            </div>
          </LTabs>
        }
      />

      <LCard
        title={<LText weight="semibold">Tooltip · Slider · Pagination</LText>}
        body={
          <LStack gap="4">
            <LTooltip trigger="Hover me" content="I am a tooltip" />
            <LSlider value="40" />
            <LPagination onPageChange={(detail) => setPage((detail as { page: number }).page)} />
            <LText size="sm">Current page: {page}</LText>
          </LStack>
        }
      />

      <LCard
        title={<LText weight="semibold">Accordion</LText>}
        body={
          <LAccordion>
            <div data-part="item" data-state="collapsed">
              <button data-part="trigger">What is Faqir?</button>
              <div data-part="content" hidden>
                A zero-class, manifest-driven UI framework.
              </div>
            </div>
            <div data-part="item" data-state="collapsed">
              <button data-part="trigger">Why bindings?</button>
              <div data-part="content" hidden>
                So React apps get typed components over the exact same contract.
              </div>
            </div>
          </LAccordion>
        }
      />

      <LSeparator />
      <LText size="sm">
        Seven recipes + eight primitives, styled entirely by faqir.default.css.
      </LText>
    </LStack>
  );
}

// packages/vue/examples/demo/App.vue
<script setup lang="ts">
// Demo page for @faqir-ui/vue (task 0.6-13 acceptance): eight generated
// components — five recipes (dialog, alert-dialog, tabs, accordion, toast)
// and three primitives (button, card, badge) — running against the real
// Faqir CSS bundle (@faqir-ui/core/dist/faqir.default.css, loaded by
// serve.ts). Run with: bun packages/vue/examples/demo/serve.ts
import { ref } from "vue";
import {
  LButton,
  LCard,
  LBadge,
  LDialog,
  LAlertDialog,
  LTabs,
  LAccordion,
  LToast,
} from "../../src/index";

const dialog = ref<InstanceType<typeof LDialog>>();
const alertDialog = ref<InstanceType<typeof LAlertDialog>>();
const toast = ref<InstanceType<typeof LToast>>();
const lastEvent = ref("none yet");

function onConfirm(detail: { variant: string }) {
  lastEvent.value = `@confirm (variant: ${detail.variant})`;
  toast.value!.add({ message: "Row deleted.", tone: "success" });
}

function onCancel(detail: { reason: string }) {
  lastEvent.value = `@cancel (reason: ${detail.reason})`;
}
</script>

<template>
  <main style="max-inline-size: 56rem; margin-inline: auto; padding: var(--space-8); display: grid; gap: var(--space-6)">
    <header>
      <h1>@faqir-ui/vue demo</h1>
      <p>
        Generated Vue 3 components over the real Faqir CSS bundle.
        Last controller event: <LBadge variant="outline">{{ lastEvent }}</LBadge>
      </p>
    </header>

    <LCard>
      <template #title>Dialog recipe</template>
      <template #body>
        <p>
          The in-template trigger is controller-wired; the outline button opens
          it through the exposed ref API (<code>dialog.open()</code>, §11.2).
        </p>
        <LDialog ref="dialog" id="demo-dialog" size="sm" title="Edit profile">
          <template #trigger>Open dialog</template>
          <template #body>
            <p>Server-renderable markup; the controller attached on mount.</p>
          </template>
          <template #footer>
            <LButton variant="outline" @click="dialog!.close()">Done</LButton>
          </template>
        </LDialog>
        <LButton variant="outline" @click="dialog!.open()">Open via ref</LButton>
      </template>
    </LCard>

    <LCard>
      <template #title>Alert-dialog recipe</template>
      <template #body>
        <p>Confirm/cancel re-emit as Vue events with payloads.</p>
        <LAlertDialog
          ref="alertDialog"
          id="demo-alert"
          title="Delete this row?"
          description="This action cannot be undone."
          confirmText="Delete"
          cancelText="Keep it"
          @confirm="onConfirm"
          @cancel="onCancel"
        >
          <template #trigger>Delete row…</template>
        </LAlertDialog>
      </template>
    </LCard>

    <LCard>
      <template #title>Tabs recipe</template>
      <template #body>
        <LTabs id="demo-tabs">
          <div data-part="list" role="tablist">
            <button data-part="trigger" role="tab" id="demo-tabs-tab-1" aria-controls="demo-tabs-panel-1" aria-selected="true">Overview</button>
            <button data-part="trigger" role="tab" id="demo-tabs-tab-2" aria-controls="demo-tabs-panel-2" aria-selected="false" tabindex="-1">Settings</button>
          </div>
          <div data-part="panel" role="tabpanel" id="demo-tabs-panel-1" aria-labelledby="demo-tabs-tab-1">
            Keyboard-navigable tabs, controller attached by the wrapper.
          </div>
          <div data-part="panel" role="tabpanel" id="demo-tabs-panel-2" aria-labelledby="demo-tabs-tab-2" hidden>
            Settings panel content.
          </div>
        </LTabs>
      </template>
    </LCard>

    <LCard>
      <template #title>Accordion recipe</template>
      <template #body>
        <LAccordion id="demo-accordion">
          <div data-part="item" data-state="collapsed">
            <button data-part="trigger" aria-expanded="false" aria-controls="demo-acc-1">
              <span>What is Faqir UI?</span>
              <span data-part="icon" aria-hidden="true">▾</span>
            </button>
            <div data-part="content" id="demo-acc-1" role="region" hidden>
              A zero-class, manifest-driven UI system — these Vue components are generated from those manifests.
            </div>
          </div>
          <div data-part="item" data-state="collapsed">
            <button data-part="trigger" aria-expanded="false" aria-controls="demo-acc-2">
              <span>Does it ship CSS in this package?</span>
              <span data-part="icon" aria-hidden="true">▾</span>
            </button>
            <div data-part="content" id="demo-acc-2" role="region" hidden>
              No — this page loads @faqir-ui/core/dist/faqir.default.css, the same bundle plain-HTML projects use.
            </div>
          </div>
        </LAccordion>
      </template>
    </LCard>

    <LToast ref="toast" id="demo-toast" position="bottom-right" />
  </main>
</template>
